version: '3.9'

services:
  autenticador:
    image: autenticador
    container_name: autenticador
    build:
      context: ./
    dns:
      - 8.8.8.8
    networks:
      - autenticador_net
      - app_net
    ports:
      - "8080:8080"

networks:
  app_net:
    name: app_net
    driver: bridge
  autenticador_net:
    name: autenticador_net
    driver: bridge