name: CI MediSupply Authenticator Develop

on:
  push:
    branches:
      - "feature**"

jobs:
  medisupply-authenticator-test:
    name: MediSupply Authenticator Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-flask
      - name: Run unit tests
        run: pytest tests/unit/ -v
      - name: Run integration tests
        run: pytest tests/integration/ -v
      - name: Code coverage
        run: |
          pytest --cov=app --cov-report=term-missing

  medisupply-authenticator-merge-develop:
    name: Merge to develop
    needs: medisupply-authenticator-test
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        if: ${{ contains(github.event.head_commit.message, 'FINALIZADO') }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.event.ref }}
          target-branch: develop