name: CI MediSupply Authenticator Develop

on:
  push:
    branches:
      - "feature**"

jobs:
  medisupply-authenticator-test:
    name: MediSupply Authenticator Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest discover -s tests
      - name: Code coverage
        run: |
          coverage run -m unittest
          coverage report -m

  medisupply-authenticator-merge-develop:
    name: Merge to develop
    needs: medisupply-authenticator-test
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        if: ${{ contains(github.event.head_commit.message, 'FINALIZADO') }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.event.ref }}
          target-branch: develop