name: CI MediSupply Authenticator Release

on:
  push:
    branches:
      - "feature**"

jobs:
  medisupply-authenticator-deploy-release:
    name: Deploy to release
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
    steps:
      - name: Wait merge feature to develop
        run: sleep 120s
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release"
      - name: Merge develop to release
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: release
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-flask
      - name: Run unit tests
        run: pytest tests/unit/ -v
      - name: Run integration tests
        run: pytest tests/integration/ -v
      - name: Code coverage
        run: |
          pytest --cov=app --cov-report=term-missing

  medisupply-authenticator-deploy-main:
    name: Deploy to main
    needs: medisupply-authenticator-deploy-release
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main